# Standard user .profile file.
# V 0.1, 25-Sep-96 SJA
# based on Login V 2.0, 11-Sep-96 DAPM.
# manded by DA (13-dec-00)
#
# ************************************************************************
#                           DO NOT EDIT THIS FILE
#
# if you wish to have your own .bash_profile (if you are using bash),
# then create a file called .bash_profile.local
# ************************************************************************

# See if there is a 'nearby' profile script in /usr/local.
# Failing that, source the global one under /apps

if [ -r "/usr/local/template/login.bash" ] ; then
	. "/usr/local/template/login.bash"
else
	echo ""
	echo "Warning: cannot access any system-wide profile script"
	echo "Your PATH and environment variables may not be correctly set"
	echo ""
	# if we fail to read the system-wise one, at least try
	# to source the local one
	if [ -r ".bash_profile.local" ] ; then
		echo "executing .bash_profile.local"
		. ".bash_profile.local"
	fi
fi
